-- Invoice contacts which are NOT marked as billing OCs primary contact
SELECT OC.ROW_ID,A.FST_NAME, A.LAST_NAME,BILL_OC.ACCNT_TYPE_CD, A.ROW_ID, BILL_OC.PR_CON_ID, OC.*   FROM SIEBEL.S_CONTACT A,
SIEBEL.S_PARTY_PER B,
SIEBEL.S_PARTY_PER_DTL C, SIEBEL.S_ORG_EXT BILL_OC, SIEBEL.S_ORG_EXT OC
WHERE A.ROW_ID = B.PERSON_ID 
AND BILL_OC.ROW_ID = B.PARTY_ID
AND B.ROW_ID = C.PAR_ROW_ID 
AND BILL_OC.PAR_OU_ID = OC.ROW_ID
AND C.RELATION_TYPE_CD = 'Invoice Contact'
--AND OC.ROW_ID = '1-1QJJAK'
AND A.ROW_ID <> BILL_OC.PR_CON_ID
AND OC.CUST_STAT_CD = 'Active'
AND OC.ACCNT_TYPE_CD = 'Customer'
AND BILL_OC.ACCNT_TYPE_CD = 'Billing'

-- Default usage contact marked as primary
SELECT OC.ROW_ID,A.FST_NAME, A.LAST_NAME,BILL_OC.ACCNT_TYPE_CD, A.ROW_ID, BILL_OC.PR_CON_ID,C.RELATION_TYPE_CD  FROM SIEBEL.S_CONTACT A,
SIEBEL.S_PARTY_PER B,
SIEBEL.S_PARTY_PER_DTL C, SIEBEL.S_ORG_EXT BILL_OC, SIEBEL.S_ORG_EXT OC
WHERE A.ROW_ID = B.PERSON_ID 
AND BILL_OC.ROW_ID = B.PARTY_ID
AND B.ROW_ID = C.PAR_ROW_ID 
AND BILL_OC.PAR_OU_ID = OC.ROW_ID
--AND C.RELATION_TYPE_CD <> 'Invoice Contact'
--AND OC.ROW_ID = '1-1QJJAK'
AND A.ROW_ID = BILL_OC.PR_CON_ID
AND OC.ACCNT_TYPE_CD = 'Customer'
AND BILL_OC.ACCNT_TYPE_CD = 'Billing'
AND NOT EXISTS (SELECT 'X' FROM SIEBEL.S_PARTY_PER_DTL X
     WHERE X.PAR_ROW_ID = C.PAR_ROW_ID 
     AND RELATION_TYPE_CD = 'Invoice Contact')


-- Contact marked as parimary contact without any role
SELECT OC.ROW_ID,BILL_OC.name FA_NAME, A.FST_NAME, A.LAST_NAME,BILL_OC.ACCNT_TYPE_CD, A.ROW_ID, BILL_OC.PR_CON_ID,C.RELATION_TYPE_CD 
FROM SIEBEL.S_CONTACT A,
SIEBEL.S_PARTY_PER B,
SIEBEL.S_PARTY_PER_DTL C, SIEBEL.S_ORG_EXT BILL_OC, SIEBEL.S_ORG_EXT OC
WHERE A.ROW_ID = B.PERSON_ID 
AND BILL_OC.ROW_ID = B.PARTY_ID
AND B.ROW_ID = C.PAR_ROW_ID(+) 
AND BILL_OC.PAR_OU_ID = OC.ROW_ID
--AND C.RELATION_TYPE_CD <> 'Invoice Contact'
--AND OC.ROW_ID = '1-1QJJAK'
AND A.ROW_ID = BILL_OC.PR_CON_ID
AND OC.ACCNT_TYPE_CD = 'Customer'
AND BILL_OC.ACCNT_TYPE_CD = 'Billing'
AND NOT EXISTS (SELECT 'X' FROM SIEBEL.S_PARTY_PER_DTL X
     WHERE X.PAR_ROW_ID = C.PAR_ROW_ID 
    )

