
SELECT A.CREATED,a.created_by, A.BU_ID,A.X_ORDER_SUB_TYPE,  ORDER_NUM, STATUS_CD, AGREE_NUM, STAT_CD 
, RANK() OVER (PARTITION BY B.AGREE_NUM ORDER BY a.rev_num desc) AS r
FROM
SIEBEL.S_ORDER A, SIEBEL.S_DOC_AGREE B
WHERE A.AGREE_ID = B.ROW_ID
AND A.X_ORDER_SUB_TYPE = 'New Purchase'
AND B.ROW_ID IN(
select agree_id from siebel.s_order 
where bu_id in ( '1-TN9AV', '1-TN9AP')
and X_ORDER_SUB_TYPE = 'New Purchase'
and agree_id IS NOT NULL
group by X_ORDER_SUB_TYPE, agree_id 
having count(*) > 1)
ORDER BY A.CREATED desc
--ORDER BY AGREE_NUM DESC,  A.CREATED desc


/*
SELECT A.CREATED,a.created_by,C.NAME OC_NAME, C.INTEGRATION_ID OC_PGUID,E.NAME FA_NAME, E.INTEGRATION_ID FA_PGUID,   D.NAME BU_NAME, A.BU_ID,A.X_ORDER_SUB_TYPE,  A.ORDER_NUM, A.STATUS_CD, B.AGREE_NUM, B.STAT_CD
, RANK() OVER (PARTITION BY B.AGREE_NUM ORDER BY a.rev_num desc) AS r
FROM
SIEBEL.S_ORDER A, SIEBEL.S_DOC_AGREE B,
SIEBEL.S_ORG_EXT C,
SIEBEL.S_BU D,
SIEBEL.S_ORG_EXT E
WHERE A.AGREE_ID = B.ROW_ID
AND A.X_ORDER_SUB_TYPE = 'New Purchase'
AND B.TARGET_OU_ID = C.ROW_ID
AND B.BU_ID = D.ROW_ID
AND A.BILL_ACCNT_ID = E.ROW_ID
AND B.ROW_ID IN(
select agree_id from siebel.s_order 
where bu_id in ( '1-TN9AV', '1-TN9AP')
and X_ORDER_SUB_TYPE = 'New Purchase'
and agree_id IS NOT NULL
group by X_ORDER_SUB_TYPE, agree_id 
having count(*) > 1)
--ORDER BY A.CREATED desc
ORDER BY AGREE_NUM DESC,  A.CREATED desc
/*

